version: "3"

services:
  node:
    container_name: writing-app_dev
    image: node:16-stretch
    security_opt:
      - label:disable
    user: "${UID-1000}:${GID-1000}"
    working_dir: /app
    volumes:
      - ./:/app
      - ./logs:/root/.npm/_logs
    ports:
      - "8000:8000"
    command: sh -c "
        echo 'Bootstrapping Node App'
        && npm install
        && npm run start-bg
        && npm run watchify-debug
      "
